import fs from 'fs';
import path from 'path';

// Target the glue code generated by wasm-pack target=web
const filePath = path.join(process.cwd(), 'src/core/pkg/zeno_core.js');

try {
    if (!fs.existsSync(filePath)) {
        console.warn(`⚠️ WASM glue code not found at ${filePath}. Skipping sanitization.`);
        process.exit(0);
    }

    let content = fs.readFileSync(filePath, 'utf8');

    // Pattern matches the default initialization block that triggers Vite inlining
    // if (typeof module_or_path === 'undefined') {
    //     module_or_path = new URL('zeno_core_bg.wasm', import.meta.url);
    // }
    const pattern = /if\s*\(typeof module_or_path === ['"]undefined['"]\)\s*\{\s*module_or_path\s*=\s*new\s*URL\(['"]zeno_core_bg\.wasm['"],\s*import\.meta\.url\);\s*\}/;

    const replacement = `if (typeof module_or_path === 'undefined') {
        module_or_path = new URL('zeno.wasm', import.meta.url);
    }`;

    if (pattern.test(content)) {
        content = content.replace(pattern, replacement);
        fs.writeFileSync(filePath, content);
        console.log('✅ Sanitized WASM glue code: Removed default inlined URL to prevent base64 bloat.');
    } else if (content.includes("Zeno WASM: module_or_path must be provided")) {
        console.log('ℹ️ WASM glue code already sanitized.');
    } else {
        console.warn('⚠️ WASM glue code pattern not found. Sanitization skipped. Please check src/core/pkg/zeno_core.js content.');
    }

    // Paranoid Check for Base64 / Inline WASM
    // Match common inline patterns: "data:application/wasm;base64,"
    if (content.includes("data:application/wasm") || content.match(/base64,[a-zA-Z0-9+/=]{100,}/)) {
        throw new Error('❌ CRITICAL SECURITY FAILURE: Detected inlined WASM/Base64 in glue code after sanitization! This is strictly forbidden by arch.md.');
    }
    // --- SYNC TO SRC/CLIENT/PUBLIC ---
    // Ensure Vite picks up the latest sanitized files
    const publicDir = path.join(process.cwd(), 'src/client/public');
    if (fs.existsSync(publicDir)) {
        // Copy zeno_core.js
        const publicJsPath = path.join(publicDir, 'zeno_core.js');
        fs.writeFileSync(publicJsPath, content);
        console.log(`✅ Synced sanitized zeno_core.js to ${publicJsPath}`);

        // Copy zeno.wasm (from zeno_core_bg.wasm)
        const bgWasmPath = path.join(process.cwd(), 'src/core/pkg/zeno_core_bg.wasm');
        if (fs.existsSync(bgWasmPath)) {
            const publicWasmPath = path.join(publicDir, 'zeno.wasm');
            fs.copyFileSync(bgWasmPath, publicWasmPath);
            console.log(`✅ Synced zeno.wasm to ${publicWasmPath}`);
        }
    }

} catch (e) {
    console.error('❌ Failed to sanitize WASM glue code:', e);
    process.exit(1);
}
