/*
 * Required Notice: © Copyright 2025 KSEC - Erez Kalman (kaerez[at]gmail[dot]com | www.kalman.co.il | https://github.com/zeno-security/zeno | https://github.com/kaerez)
 *
 * This software is licensed under the PolyForm Strict License 1.0.0.
 * You may obtain a copy of the License at:
 * * https://polyformproject.org/licenses/strict/1.0.0/
 *
 * SPDX-License-Identifier: PolyForm-Strict-1.0.0
 */
// Cloudflare Workers support direct import of WASM if configured
// import wasm from "../../dist/core_wasm/zeno_core_bg.wasm";
// However, standard pattern often involves checking instantiation.

// For this project, we assume we can import the glue JS generated by wasm-pack
// or the WASM module directly.
// Best compatibility: Import the generated JS glue which handles the WASM instantiation.

// @ts-ignore
import wasmModule from "./zeno.wasm";
import * as wasm from "zeno-core";

// This interface definition is added based on the user's instruction to "Update interface signature".
// It's placed here as a type definition for the 'wasm' module, assuming 'zeno-core'
// is expected to have a 'verify_proof' method with this signature.
declare module "zeno-core" {
    export function verify_proof(
        seed_hex: string,
        cycle: Uint32Array,
        y: any,
        pi: any,
        discriminant: Uint8Array,
        vdf: bigint,
        graph_bits: number
    ): boolean;
}

export async function loadWasm() {
    await wasm.default(wasmModule);
    return wasm;
}
